# Generated by Django 4.2.6 on 2023-10-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cliente', models.IntegerField()),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('endereço', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'pessoas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advogado_id', models.IntegerField()),
                ('cliente_id', models.IntegerField()),
                ('numero_processo', models.CharField(max_length=35)),
                ('proximo_prazo', models.DateTimeField()),
                ('arquivo', models.IntegerField()),
            ],
            options={
                'db_table': 'processos',
                'managed': False,
            },
        ),
    ]
